# This is a basic workflow to help you get started with Actions

name: Web

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]
    paths-ignore: [functions]
  pull_request:
    branches: [ master ]
    paths-ignore: [functions]

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - name: Install dependencies
        uses: borales/actions-yarn@v2.0.0
        with:
          cmd: install
      - name: Build Dev
        if: github.ref != 'refs/heads/master'
        uses: borales/actions-yarn@v2.0.0
        with:
          cmd: build
        env:
          REACT_APP_TOG_FIREBASE_API_KEY: ${{ secrets.DEV_REACT_APP_TOG_FIREBASE_API_KEY }}
          REACT_APP_TOG_FIREBASE_AUTH_DOMAIN: ${{secrets.DEV_REACT_APP_TOG_FIREBASE_AUTH_DOMAIN}}
          REACT_APP_TOG_FIREBASE_DATABASE_URL: ${{secrets.DEV_REACT_APP_TOG_FIREBASE_DATABASE_URL}}
          REACT_APP_TOG_FIREBASE_PROJECT_ID: ${{secrets.DEV_REACT_APP_TOG_FIREBASE_PROJECT_ID}}
          REACT_APP_TOG_FIREBASE_STORAGE_BUCKET: ${{secrets.DEV_REACT_APP_TOG_FIREBASE_STORAGE_BUCKET}}
          REACT_APP_TOG_FIREBASE_MESSAGING_SENDER_ID: ${{secrets.DEV_REACT_APP_TOG_FIREBASE_MESSAGING_SENDER_ID}}
          REACT_APP_TOG_FIREBASE_APP_ID: ${{secrets.DEV_REACT_APP_TOG_FIREBASE_APP_ID}}
          REACT_APP_TOG_FIREBASE_MEASUREMENT_ID: ${{secrets.DEV_REACT_APP_TOG_FIREBASE_MEASUREMENT_ID}}
      - name: Build Prod
        if: github.ref == 'refs/heads/master'
        uses: borales/actions-yarn@v2.0.0
        with:
          cmd: build
        env:
          REACT_APP_TOG_FIREBASE_API_KEY: ${{ secrets.PROD_REACT_APP_TOG_FIREBASE_API_KEY }}
          REACT_APP_TOG_FIREBASE_AUTH_DOMAIN: ${{secrets.PROD_REACT_APP_TOG_FIREBASE_AUTH_DOMAIN}}
          REACT_APP_TOG_FIREBASE_DATABASE_URL: ${{secrets.PROD_REACT_APP_TOG_FIREBASE_DATABASE_URL}}
          REACT_APP_TOG_FIREBASE_PROJECT_ID: ${{secrets.PROD_REACT_APP_TOG_FIREBASE_PROJECT_ID}}
          REACT_APP_TOG_FIREBASE_STORAGE_BUCKET: ${{secrets.PROD_REACT_APP_TOG_FIREBASE_STORAGE_BUCKET}}
          REACT_APP_TOG_FIREBASE_MESSAGING_SENDER_ID: ${{secrets.PROD_REACT_APP_TOG_FIREBASE_MESSAGING_SENDER_ID}}
          REACT_APP_TOG_FIREBASE_APP_ID: ${{secrets.PROD_REACT_APP_TOG_FIREBASE_APP_ID}}
          REACT_APP_TOG_FIREBASE_MEASUREMENT_ID: ${{secrets.PROD_REACT_APP_TOG_FIREBASE_MEASUREMENT_ID}}
      - name: Archive Build
        uses: actions/upload-artifact@master
        with:
          name: build
          path: build

  deploy:
    name: Deploy
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@master
      - name: Download Build
        uses: actions/download-artifact@master
        with:
          name: build
          path: build
      - name: Deploy Dev to Firebase
        if: github.ref != 'refs/heads/master'
        uses: w9jds/firebase-action@master
        with:
          args: deploy -P dev --only hosting
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
      - name: Deploy Prod to Firebase
        if: github.ref == 'refs/heads/master'
        uses: w9jds/firebase-action@master
        with:
          args: deploy -P prod --only hosting
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
